-- =========================================
-- AIRLINE & RAILWAY TICKET RESERVATION SYSTEM
-- SAMPLE DATA
-- =========================================

-- ADMIN DATA

INSERT INTO ADMIN (ADMIN_ID, ADMIN_NAME, EMAIL, PASSWORD)
VALUES (1, 'Ravi Sharma', 'ravi.admin@gmail.com', 'admin123');

INSERT INTO ADMIN (ADMIN_ID, ADMIN_NAME, EMAIL, PASSWORD)
VALUES (2, 'Priya Singh', 'priya.admin@gmail.com', 'admin456');


-- USER DATA

INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PHONE, PASSWORD)
VALUES (101, 'Rashi Mishra', 'rashi@gmail.com', '9876543210', 'rashi123');

INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PHONE, PASSWORD)
VALUES (102, 'Gargi Verma', 'gargi@gmail.com', '9876543211', 'gargi123');

INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PHONE, PASSWORD)
VALUES (103, 'Ansh Jain', 'ansh@gmail.com', '9876543212', 'ansh123');

INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PHONE, PASSWORD)
VALUES (104, 'Nityam Jain', 'nityam@gmail.com', '9876543213', 'nityam123');

INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PHONE, PASSWORD)
VALUES (105, 'Raina Gupta', 'raina@gmail.com', '9876543214', 'raina123');


-- TRAIN DATA

INSERT INTO TRAIN
(TRAIN_ID, TRAIN_NUMBER, TRAIN_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(1, '12001', 'Shatabdi Express', 'Bhopal', 'Delhi',
 TIMESTAMP '2026-10-01 06:00:00',
 TIMESTAMP '2026-10-01 12:30:00',
 100, 850, 1);

INSERT INTO TRAIN
(TRAIN_ID, TRAIN_NUMBER, TRAIN_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(2, '12155', 'Bhopal Express', 'Bhopal', 'Mumbai',
 TIMESTAMP '2026-10-01 08:00:00',
 TIMESTAMP '2026-10-01 20:00:00',
 100, 650, 1);

INSERT INTO TRAIN
(TRAIN_ID, TRAIN_NUMBER, TRAIN_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(3, '12533', 'Pushpak Express', 'Lucknow', 'Mumbai',
 TIMESTAMP '2026-10-02 10:00:00',
 TIMESTAMP '2026-10-03 08:00:00',
 100, 900, 2);

INSERT INTO TRAIN
(TRAIN_ID, TRAIN_NUMBER, TRAIN_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(4, '12423', 'Dibrugarh Rajdhani', 'Delhi', 'Dibrugarh',
 TIMESTAMP '2026-10-02 16:00:00',
 TIMESTAMP '2026-10-04 08:00:00',
 100, 1800, 2);

INSERT INTO TRAIN
(TRAIN_ID, TRAIN_NUMBER, TRAIN_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(5, '12627', 'Karnataka Express', 'Delhi', 'Bangalore',
 TIMESTAMP '2026-10-03 19:00:00',
 TIMESTAMP '2026-10-05 06:00:00',
 100, 1500, 1);


-- FLIGHT DATA

INSERT INTO FLIGHT
(FLIGHT_ID, FLIGHT_NUMBER, AIRLINE_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(1, '6E101', 'IndiGo', 'Delhi', 'Mumbai',
 TIMESTAMP '2026-10-01 09:00:00',
 TIMESTAMP '2026-10-01 11:15:00',
 180, 4500, 1);

INSERT INTO FLIGHT
(FLIGHT_ID, FLIGHT_NUMBER, AIRLINE_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(2, 'AI202', 'Air India', 'Delhi', 'Bangalore',
 TIMESTAMP '2026-10-01 12:00:00',
 TIMESTAMP '2026-10-01 14:45:00',
 180, 5200, 2);

INSERT INTO FLIGHT
(FLIGHT_ID, FLIGHT_NUMBER, AIRLINE_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(3, '6E303', 'IndiGo', 'Mumbai', 'Bangalore',
 TIMESTAMP '2026-10-02 10:00:00',
 TIMESTAMP '2026-10-02 11:45:00',
 180, 4200, 1);

INSERT INTO FLIGHT
(FLIGHT_ID, FLIGHT_NUMBER, AIRLINE_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(4, 'UK404', 'Vistara', 'Mumbai', 'Delhi',
 TIMESTAMP '2026-10-02 15:00:00',
 TIMESTAMP '2026-10-02 17:10:00',
 180, 4800, 2);

INSERT INTO FLIGHT
(FLIGHT_ID, FLIGHT_NUMBER, AIRLINE_NAME, SOURCE, DESTINATION,
 DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, FARE, MANAGED_BY)
VALUES
(5, '6E505', 'IndiGo', 'Bangalore', 'Delhi',
 TIMESTAMP '2026-10-03 18:00:00',
 TIMESTAMP '2026-10-03 20:45:00',
 180, 5100, 1);


-- TRAIN SEAT DATA

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (1, 1, 'A1', 'AC', 'AVAILABLE');

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (2, 1, 'A2', 'AC', 'AVAILABLE');

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (3, 2, 'B1', 'SLEEPER', 'AVAILABLE');

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (4, 2, 'B2', 'SLEEPER', 'AVAILABLE');

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (5, 3, 'C1', 'AC', 'AVAILABLE');

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (6, 3, 'C2', 'AC', 'AVAILABLE');

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (7, 4, 'D1', 'AC', 'AVAILABLE');

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (8, 4, 'D2', 'AC', 'AVAILABLE');

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (9, 5, 'E1', 'SLEEPER', 'AVAILABLE');

INSERT INTO TRAIN_SEAT
(SEAT_ID, TRAIN_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (10, 5, 'E2', 'SLEEPER', 'AVAILABLE');


-- FLIGHT SEAT DATA

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (1, 1, '1A', 'ECONOMY', 'AVAILABLE');

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (2, 1, '1B', 'ECONOMY', 'AVAILABLE');

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (3, 2, '2A', 'ECONOMY', 'AVAILABLE');

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (4, 2, '2B', 'ECONOMY', 'AVAILABLE');

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (5, 3, '3A', 'ECONOMY', 'AVAILABLE');

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (6, 3, '3B', 'ECONOMY', 'AVAILABLE');

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (7, 4, '4A', 'BUSINESS', 'AVAILABLE');

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (8, 4, '4B', 'BUSINESS', 'AVAILABLE');

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (9, 5, '5A', 'ECONOMY', 'AVAILABLE');

INSERT INTO FLIGHT_SEAT
(SEAT_ID, FLIGHT_ID, SEAT_NUMBER, SEAT_CLASS, SEAT_STATUS)
VALUES (10, 5, '5B', 'ECONOMY', 'AVAILABLE');


-- BOOKING DATA

INSERT INTO BOOKING
(BOOKING_ID, PNR, USER_ID, BOOKING_TYPE, TRAIN_ID, FLIGHT_ID,
 TOTAL_AMOUNT, BOOKING_STATUS)
VALUES
(1001, 'TRN10001', 101, 'TRAIN', 1, NULL, 850, 'CONFIRMED');

INSERT INTO BOOKING
(BOOKING_ID, PNR, USER_ID, BOOKING_TYPE, TRAIN_ID, FLIGHT_ID,
 TOTAL_AMOUNT, BOOKING_STATUS)
VALUES
(1002, 'TRN10002', 102, 'TRAIN', 2, NULL, 650, 'CONFIRMED');

INSERT INTO BOOKING
(BOOKING_ID, PNR, USER_ID, BOOKING_TYPE, TRAIN_ID, FLIGHT_ID,
 TOTAL_AMOUNT, BOOKING_STATUS)
VALUES
(1003, 'TRN10003', 103, 'TRAIN', 3, NULL, 900, 'CANCELLED');

INSERT INTO BOOKING
(BOOKING_ID, PNR, USER_ID, BOOKING_TYPE, TRAIN_ID, FLIGHT_ID,
 TOTAL_AMOUNT, BOOKING_STATUS)
VALUES
(1004, 'FLT10004', 104, 'FLIGHT', NULL, 1, 4500, 'CONFIRMED');

INSERT INTO BOOKING
(BOOKING_ID, PNR, USER_ID, BOOKING_TYPE, TRAIN_ID, FLIGHT_ID,
 TOTAL_AMOUNT, BOOKING_STATUS)
VALUES
(1005, 'FLT10005', 105, 'FLIGHT', NULL, 2, 5200, 'CONFIRMED');


-- PASSENGER DATA

INSERT INTO PASSENGER
(PASSENGER_ID, BOOKING_ID, PASSENGER_NAME, AGE, GENDER, ID_PROOF)
VALUES (2001, 1001, 'Rashi Mishra', 18, 'Female', 'AADHAR001');

INSERT INTO PASSENGER
(PASSENGER_ID, BOOKING_ID, PASSENGER_NAME, AGE, GENDER, ID_PROOF)
VALUES (2002, 1001, 'Gargi Verma', 19, 'Female', 'AADHAR002');

INSERT INTO PASSENGER
(PASSENGER_ID, BOOKING_ID, PASSENGER_NAME, AGE, GENDER, ID_PROOF)
VALUES (2003, 1002, 'Ansh Jain', 20, 'Male', 'AADHAR003');

INSERT INTO PASSENGER
(PASSENGER_ID, BOOKING_ID, PASSENGER_NAME, AGE, GENDER, ID_PROOF)
VALUES (2004, 1003, 'Nityam Jain', 19, 'Male', 'AADHAR004');

INSERT INTO PASSENGER
(PASSENGER_ID, BOOKING_ID, PASSENGER_NAME, AGE, GENDER, ID_PROOF)
VALUES (2005, 1004, 'Raina Gupta', 20, 'Female', 'AADHAR005');

INSERT INTO PASSENGER
(PASSENGER_ID, BOOKING_ID, PASSENGER_NAME, AGE, GENDER, ID_PROOF)
VALUES (2006, 1005, 'Rashi Mishra', 18, 'Female', 'AADHAR006');


-- PAYMENT DATA

INSERT INTO PAYMENT
(PAYMENT_ID, BOOKING_ID, PAYMENT_METHOD, PAYMENT_AMOUNT,
 PAYMENT_STATUS, TRANSACTION_ID)
VALUES (3001, 1001, 'UPI', 850, 'SUCCESS', 'TXN10001');

INSERT INTO PAYMENT
(PAYMENT_ID, BOOKING_ID, PAYMENT_METHOD, PAYMENT_AMOUNT,
 PAYMENT_STATUS, TRANSACTION_ID)
VALUES (3002, 1002, 'CARD', 650, 'SUCCESS', 'TXN10002');

INSERT INTO PAYMENT
(PAYMENT_ID, BOOKING_ID, PAYMENT_METHOD, PAYMENT_AMOUNT,
 PAYMENT_STATUS, TRANSACTION_ID)
VALUES (3003, 1003, 'UPI', 900, 'SUCCESS', 'TXN10003');

INSERT INTO PAYMENT
(PAYMENT_ID, BOOKING_ID, PAYMENT_METHOD, PAYMENT_AMOUNT,
 PAYMENT_STATUS, TRANSACTION_ID)
VALUES (3004, 1004, 'NET BANKING', 4500, 'SUCCESS', 'TXN10004');

INSERT INTO PAYMENT
(PAYMENT_ID, BOOKING_ID, PAYMENT_METHOD, PAYMENT_AMOUNT,
 PAYMENT_STATUS, TRANSACTION_ID)
VALUES (3005, 1005, 'UPI', 5200, 'SUCCESS', 'TXN10005');


-- CANCELLATION DATA

INSERT INTO CANCELLATION
(CANCELLATION_ID, BOOKING_ID, REASON, REFUND_AMOUNT)
VALUES
(4001, 1003, 'Change of travel plan', 750);

COMMIT;