CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PHONE VARCHAR2(15),
    PASSWORD VARCHAR2(100) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);
CREATE TABLE ADMIN (
    ADMIN_ID NUMBER PRIMARY KEY,
    ADMIN_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL
);
CREATE TABLE TRAIN (
    TRAIN_ID NUMBER PRIMARY KEY,
    TRAIN_NUMBER VARCHAR2(20) UNIQUE NOT NULL,
    TRAIN_NAME VARCHAR2(100) NOT NULL,
    SOURCE VARCHAR2(100) NOT NULL,
    DESTINATION VARCHAR2(100) NOT NULL,
    DEPARTURE_TIME TIMESTAMP,
    ARRIVAL_TIME TIMESTAMP,
    TOTAL_SEATS NUMBER NOT NULL,
    FARE NUMBER(10,2) NOT NULL,
    MANAGED_BY NUMBER,

    CONSTRAINT FK_TRAIN_ADMIN
        FOREIGN KEY (MANAGED_BY)
        REFERENCES ADMIN(ADMIN_ID)
);
CREATE TABLE FLIGHT (
    FLIGHT_ID NUMBER PRIMARY KEY,
    FLIGHT_NUMBER VARCHAR2(20) UNIQUE NOT NULL,
    AIRLINE_NAME VARCHAR2(100) NOT NULL,
    SOURCE VARCHAR2(100) NOT NULL,
    DESTINATION VARCHAR2(100) NOT NULL,
    DEPARTURE_TIME TIMESTAMP,
    ARRIVAL_TIME TIMESTAMP,
    TOTAL_SEATS NUMBER NOT NULL,
    FARE NUMBER(10,2) NOT NULL,
    MANAGED_BY NUMBER,

    CONSTRAINT FK_FLIGHT_ADMIN
        FOREIGN KEY (MANAGED_BY)
        REFERENCES ADMIN(ADMIN_ID)
);
CREATE TABLE TRAIN_SEAT (
    SEAT_ID NUMBER PRIMARY KEY,
    TRAIN_ID NUMBER NOT NULL,
    SEAT_NUMBER VARCHAR2(10) NOT NULL,
    SEAT_CLASS VARCHAR2(30),
    SEAT_STATUS VARCHAR2(20) DEFAULT 'AVAILABLE',

    CONSTRAINT FK_TRAIN_SEAT
        FOREIGN KEY (TRAIN_ID)
        REFERENCES TRAIN(TRAIN_ID),

    CONSTRAINT UQ_TRAIN_SEAT
        UNIQUE (TRAIN_ID, SEAT_NUMBER)
);
CREATE TABLE FLIGHT_SEAT (
    SEAT_ID NUMBER PRIMARY KEY,
    FLIGHT_ID NUMBER NOT NULL,
    SEAT_NUMBER VARCHAR2(10) NOT NULL,
    SEAT_CLASS VARCHAR2(30),
    SEAT_STATUS VARCHAR2(20) DEFAULT 'AVAILABLE',

    CONSTRAINT FK_FLIGHT_SEAT
        FOREIGN KEY (FLIGHT_ID)
        REFERENCES FLIGHT(FLIGHT_ID),

    CONSTRAINT UQ_FLIGHT_SEAT
        UNIQUE (FLIGHT_ID, SEAT_NUMBER)
);
CREATE TABLE BOOKING (
    BOOKING_ID NUMBER PRIMARY KEY,
    PNR VARCHAR2(20) UNIQUE NOT NULL,
    USER_ID NUMBER NOT NULL,
    BOOKING_TYPE VARCHAR2(10) NOT NULL,
    TRAIN_ID NUMBER,
    FLIGHT_ID NUMBER,
    BOOKING_DATE DATE DEFAULT SYSDATE,
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
    BOOKING_STATUS VARCHAR2(20) DEFAULT 'CONFIRMED',

    CONSTRAINT FK_BOOKING_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_BOOKING_TRAIN
        FOREIGN KEY (TRAIN_ID)
        REFERENCES TRAIN(TRAIN_ID),

    CONSTRAINT FK_BOOKING_FLIGHT
        FOREIGN KEY (FLIGHT_ID)
        REFERENCES FLIGHT(FLIGHT_ID),

    CONSTRAINT CHK_BOOKING_TYPE
        CHECK (BOOKING_TYPE IN ('TRAIN', 'FLIGHT')),

    CONSTRAINT CHK_BOOKING_TRANSPORT
        CHECK (
            (BOOKING_TYPE = 'TRAIN'
             AND TRAIN_ID IS NOT NULL
             AND FLIGHT_ID IS NULL)
            OR
            (BOOKING_TYPE = 'FLIGHT'
             AND FLIGHT_ID IS NOT NULL
             AND TRAIN_ID IS NULL)
        )
);
CREATE TABLE PASSENGER (
    PASSENGER_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL,
    PASSENGER_NAME VARCHAR2(100) NOT NULL,
    AGE NUMBER,
    GENDER VARCHAR2(20),
    ID_PROOF VARCHAR2(50),

    CONSTRAINT FK_PASSENGER_BOOKING
        FOREIGN KEY (BOOKING_ID)
        REFERENCES BOOKING(BOOKING_ID)
);
CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER UNIQUE NOT NULL,
    PAYMENT_DATE DATE DEFAULT SYSDATE,
    PAYMENT_METHOD VARCHAR2(30) NOT NULL,
    PAYMENT_AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'SUCCESS',
    TRANSACTION_ID VARCHAR2(50) UNIQUE,

    CONSTRAINT FK_PAYMENT_BOOKING
        FOREIGN KEY (BOOKING_ID)
        REFERENCES BOOKING(BOOKING_ID)
);
CREATE TABLE CANCELLATION (
    CANCELLATION_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER UNIQUE NOT NULL,
    CANCELLATION_DATE DATE DEFAULT SYSDATE,
    REASON VARCHAR2(200),
    REFUND_AMOUNT NUMBER(10,2),

    CONSTRAINT FK_CANCELLATION_BOOKING
        FOREIGN KEY (BOOKING_ID)
        REFERENCES BOOKING(BOOKING_ID)
);